on: [push]

name: Linux_Container_Node_Workflow



jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    # checkout the repo
    - name: 'Checkout Github Action'
      uses: actions/checkout@master

    - uses: azure/docker-login@v1
      with:
        login-server: kumaraksh1.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - run: |
        docker build . -t kumaraksh1.azurecr.io/nodejssampleapp:latest
        docker push kumaraksh1.azurecr.io/nodejssampleapp:latest 

    - uses: azure/webapps-deploy@v2
      with:
        app-name: 'node-docker-aksh'
        publish-profile: ${{ secrets.azureWebAppPublishProfile }}
        images: 'kumaraksh1.azurecr.io/nodejssampleapp:latest'
